version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgres/${POSTGRES_DB}
    ports:
      - "5432:5432"
  app:
    container_name: smart-meter-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db